### ISSUE TITLE
Disallow referencing non-existent files in .drstring.toml

### ISSUE THREAD

**Issue by rebello95** [dduan/DrString#163]
At the moment, the `.drstring.toml` file can reference files that do not exist and DrString doesn't complain. It'd be nice if it instead failed similarly to how it does when listing files in `.drstring.toml` that contain no violations.

**Comment by keith** [comment]
I thought at some point this worked?

**Comment by rebello95** [comment]
AFAIK it only disallowed listing files that had no violations, not listing non-existent files
